# Generated by Django 4.1.1 on 2022-09-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_head_image_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='head_image',
        ),
    ]
